version: '3.8'

services:
  db:
    image: mariadb:10.5
    container_name: mariadb_db
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: .
    container_name: django_app
    command: ./wait-for-it.sh db:3306 -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./wait-for-it.sh:/wait-for-it.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=db

volumes:
  db_data:
